Vagrant.configure(2) do |config|

  config.vm.define "webserver" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "webserver"
    web.vm.network "private_network", ip: "10.0.0.10"
    web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "webserver"
      end
      web.vm.synced_folder ".", "/var/www/html/Fileshare"
      web.vm.provision "shell", path: "webserver.sh"
  end
  
  config.vm.define "client01" do |client01|
    client01.vm.box = "ubuntu/xenial64"
    client01.vm.hostname = "client-int"
    client01.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    client01.vm.network "private_network", ip: "10.0.0.20"
      client01.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "client-int"
      end
      client01.vm.synced_folder ".", "/var/www/html/Fileshare"
      client01.vm.provision "shell", path: "client-int.sh"
  end
  
  config.vm.define "client02" do |client02|
    client02.vm.box = "ubuntu/xenial64"
    client02.vm.hostname = "client-ext"
    client02.vm.network "private_network", ip: "80.0.0.20"
       client02.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "client-ext"
      end
      client02.vm.synced_folder ".", "/var/www/html/Fileshare"
      client02.vm.provision "shell", path: "client-ext.sh"
  end
end

